# Gradle
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true

# AndroidX / Android Gradle Plugin
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
android.enableR8.fullMode=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true
kotlin.caching.enabled=true
kotlin.daemon.jvmargs=-Xmx2048m
